### ISSUE TITLE
Question: JS interactions CKAN/wet-boew

### ISSUE THREAD

**Issue by nfee006** [open-data/ckanext-canada#1191]
Hello, not an issue - just a question.

Have you ever run into issues with interactions between CKAN and JS elements from wet-boew/GCWeb? We're trying to track down a mystery interaction that's preventing the "share this page" wet-boew button JS event from working in the CSA CKAN portal. I noticed that open.canada.ca doesn't make use of this button and was wondering if you guys had tried but ran into issues. I'm already in touch with the GCWeb team but thought I'd check with you guys as well. Thanks! 

![image](https://user-images.githubusercontent.com/11013061/117861932-02e37e00-b260-11eb-88cd-013bc05ce88c.png)

**Comment by RabiaSajjad** [comment]
Hello, 

We have also run into similar issues for triggering modal pop-up window and found that WET is loading an older version of JQuery [2.2.4](https://github.com/wet-boew/wet-boew/blob/ee1174b15b611974444ccf2d2a94c133b035081f/package.json#L41) while CKAN loads a newer version of JQuery [3.5](https://github.com/ckan/ckan/blob/3d28c4f5acd84067fe22ef74a0ceb1f399ae92f3/package.json#L14). We have explored the option to request WET to [upgrade the version of JQuery](https://github.com/wet-boew/wet-boew/issues/8557). In the meanwhile, we are using a workaround to trigger a modal window using [bootstrap](https://getbootstrap.com/docs/4.0/components/modal/) instead of WET. As an example, we replaced the WET's modal classes with bootstrap classes in this commit https://github.com/open-data/ckanext-canada/commit/9d5c2f9a38d8a5db76e964c73a39f2b964871395 and it has resolved the issue for us.

Hope it helps!

**Comment by duboisp** [comment]
It is possible to not use the magnific popup for the share this page widget and use instead the overlay plugin.

It will only require someone to send a PR to make that change into the wet-boew share plugin here:
* https://github.com/wet-boew/wet-boew/blob/master/src/plugins/share/share.js#L174
* https://github.com/wet-boew/wet-boew/blob/master/src/plugins/share/share.js#L216
